module: FitnessUnits
author: Kevin A. Hoogheem
github_url: https://github.com/FitnessKit/FitnessUnits

readme: README.md

output: docs
clean: true
theme: jony

copyright: '© 2017 Kevin A. Hoogheem'

xcodebuild_arguments: [-scheme,FitnessUnits-Package]

